---
site_name: 'jinja-file-renderer'

theme:
  name: 'readthedocs'

nav:
  - 'Home': 'index.md'
  - 'User-Guide': 'user-guide.md'
  - 'Developer-Guides':
      - 'Developer-Guide': 'developer-guides/developer-guide.md'
      - 'Release-Guide': 'developer-guides/release-guide.md'
  - 'About':
      - 'License': 'about/license.md'
      - 'Release Notes': 'about/release-notes.md'
