---
name: 'feature-branch-workflow'
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches-ignore:
      - 'main'
      - 'develop'
      - 'support/**'
jobs:
  lint:
    name: 'lint'
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-python@v5'
        with:
          python-version: '3.12'
      - name: 'Install hatch'
        run: 'pipx install hatch~=1.12.0'
      - name: 'Lint'
        run: 'hatch fmt --check'
  test:
    needs:
      - 'lint'
    name: "test"
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: 'actions/setup-python@v5'
        with:
          python-version: '3.12'
      - name: 'Install hatch'
        run: 'pipx install hatch~=1.12.0'
      - name: 'Test'
        run: 'hatch test --all --cover'
      - name: 'Collect coverage'
        uses: 'romeovs/lcov-reporter-action@v0.4.0'
        with:
          lcov-file: 'lcov.info'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: 'Build App'
        run: 'hatch build'
      - uses: 'actions/upload-artifact@v4'
        with:
          name: 'module'
          path: 'dist/jinja_file_renderer-*.tar.gz'
          compression-level: 0  # no compression
          if-no-files-found: 'error'
          retention-days: 5
      - uses: 'actions/upload-artifact@v4'
        with:
          name: 'wheel'
          path: 'dist/jinja_file_renderer-*.whl'
          compression-level: 0  # no compression
          if-no-files-found: 'error'
          retention-days: 5
      - name: 'Build Docs'
        run: 'hatch run mkdocs:build-archive'
      - uses: 'actions/upload-artifact@v4'
        with:
          name: 'documentation'
          path: 'jinja-file-renderer-doc-*.tar.xz'
          compression-level: 0  # no compression
          if-no-files-found: 'error'
          retention-days: 5
